language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          dist: trusty
          python: "2.6"
        - os: linux
          sudo: required
          dist: trusty
          python: "2.7"
        - os: linux
          sudo: required
          dist: trusty
          python: "3.3"
        - os: linux
          sudo: required
          dist: trusty
          python: "3.4"
        - os: linux
          sudo: required
          dist: trusty
          python: "3.5"
        - os: linux
          sudo: required
          dist: trusty
          python: "3.5-dev"
        - os: linux
          sudo: required
          dist: trusty
          python: "nightly"
        # Use generic language for osx
        - os: osx
          language: generic
before_install:
    # Install iperf3 on linux
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y iperf3 ;fi
    # Install iperf3, python3 and activate venv for osx
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/esnet/iperf.git ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd iperf ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./bootstrap.sh ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure && make && make install ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd .. ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3 ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate ;fi
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=iperf3 setup.py test"
after_success:
    coveralls
