language: python
os: linux
sudo: required
dist: trusty
python:
    - "2.7"
    - "3.6"
env:
  - IPERF_VERSION="3.0.6"
  - IPERF_VERSION="3.0.7"
  - IPERF_VERSION="3.0.8"
  - IPERF_VERSION="3.0.9"
  - IPERF_VERSION="3.0.10"
  - IPERF_VERSION="3.0.11"
  - IPERF_VERSION="3.0.12"
  - IPERF_VERSION="3.1"
  - IPERF_VERSION="3.1.1"
  - IPERF_VERSION="3.1.2"
  - IPERF_VERSION="3.1.3"
  - IPERF_VERSION="3.1.4"
  - IPERF_VERSION="3.1.5"
  - IPERF_VERSION="3.1.6"
  - IPERF_VERSION="3.1.7"
  - IPERF_VERSION="3.2"
  - IPERF_VERSION="3.3"
before_install:
    # Download the various available iperf3 sources
    - if [[ "$IPERF_VERSION" == "3.0.6" ]]; then wget https://iperf.fr/download/source/iperf-3.0.6-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.7" ]]; then wget https://iperf.fr/download/source/iperf-3.0.7-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.8" ]]; then wget https://iperf.fr/download/source/iperf-3.0.8-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.9" ]]; then wget https://iperf.fr/download/source/iperf-3.0.9-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.10" ]]; then wget https://iperf.fr/download/source/iperf-3.0.10-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.11" ]]; then wget https://iperf.fr/download/source/iperf-3.0.11-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.12" ]]; then wget https://iperf.fr/download/source/iperf-3.0.12-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1" ]]; then wget https://iperf.fr/download/source/iperf-3.1-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.1" ]]; then wget https://iperf.fr/download/source/iperf-3.1.1-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.2" ]]; then wget https://iperf.fr/download/source/iperf-3.1.2-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.3" ]]; then wget https://iperf.fr/download/source/iperf-3.1.3-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.4" ]]; then wget https://iperf.fr/download/source/iperf-3.1.4-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.5" ]]; then wget https://iperf.fr/download/source/iperf-3.1.5-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.6" ]]; then wget https://iperf.fr/download/source/iperf-3.1.6-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.7" ]]; then wget https://iperf.fr/download/source/iperf-3.1.7-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.2" ]]; then wget https://iperf.fr/download/source/iperf-3.2-source.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.3" ]]; then wget https://iperf.fr/download/source/iperf-3.3-source.tar.gz ;fi

    # Install iperf version selected above
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xvf iperf-*-source.tar.gz ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd iperf-*/ ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bootstrap.sh ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure && make && sudo make install ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd .. ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=/usr/local/lib ;fi
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=iperf3 setup.py test"
after_success:
    coveralls
