sudo: required
dist: trusty
language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y iperf3
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=iperf3 setup.py test"
after_success:
    coveralls
