sudo: required
dist: trusty
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y iperf3 ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install iperf3 ;fi
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=iperf3 setup.py test"
after_success:
    coveralls
